/**
 * Host half of the dsh-aris family aggregate: no host behavior of its own.
 * The plugin rows that activate the family members live in cordis.patch.yml
 * (AUTO-GENERATED by scripts/aggregate.mjs from aggregate.yml — do not edit
 * by hand). Note that @aimercat/dsh-memory is deliberately NOT part of the
 * patch: it ships as a dependency so the aris preset can resolve it, but it
 * stays preset-gated (agent plane) instead of mounting globally (host plane).
 */
import type { Context } from '@deepseek-ai/cordis'

/** Required services: none. */
export const inject = [] as const

/** Host plugin body: nothing to do. */
export function apply(_ctx: Context): void {}
